### ISSUE TITLE
für arena stimmen mit einem spieler

### ISSUE THREAD

**Issue by svenlr** [Machplatzwennduunsaufderstrassesiehst/Mental#14]
@m1a9l9t7e 
FATAL EXCEPTION: Thread-19493
                                                                   Process: de.soeiner.mental, PID: 12411
                                                                   java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                                       at de.soeiner.mental.ArenaGameMode.prepareGame(ArenaGameMode.java:25)
                                                                       at de.soeiner.mental.Game.run(Game.java:304)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by m1a9l9t7e** [comment]
danke, hab den fehler gefixt
